// GENERATED by scripts/bump_version.sh — do not edit manually.
const String appVersion = '0.1.0';
const int appBuildNumber = 1;

// Injected at build time via --dart-define; defaults to '' / 'dev' for local builds.
const String _buildDateEnv =
    String.fromEnvironment('BUILD_DATE', defaultValue: '');
const String buildCommit =
    String.fromEnvironment('BUILD_COMMIT', defaultValue: 'dev');

/// CI injects an ISO date; local dev builds show date + time from DateTime.now().
String get buildDate {
  if (_buildDateEnv.isNotEmpty) return _buildDateEnv;
  final now = DateTime.now();
  return '${now.year}-${_pad(now.month)}-${_pad(now.day)} '
      '${_pad(now.hour)}:${_pad(now.minute)}';
}

String _pad(int n) => n.toString().padLeft(2, '0');
